# Generated by Django 5.2.3 on 2026-05-13 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('project_lead', 'Project Lead'), ('ui_ux_designer', 'UI/UX Designer'), ('developer', 'Developer'), ('tester', 'Tester'), ('qa', 'QA'), ('deployment_team', 'Deployment Team'), ('delivery_team', 'Delivery Team')], max_length=25)),
                ('permission', models.CharField(choices=[('create_task', 'Create Task'), ('delete_task', 'Delete Task'), ('assign_task', 'Assign Task')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('product', 'Product'), ('design', 'Design'), ('operations', 'Operations'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('project_url', models.URLField(blank=True, help_text='Link to documentation, repo, or external resource', max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Project icon or logo', null=True, upload_to='project_avatars/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], default='p3', max_length=10, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('project_type', models.CharField(choices=[('kanban', 'Kanban'), ('scrum', 'Scrum')], default='kanban', max_length=10)),
                ('key_prefix', models.CharField(default='TF', max_length=10)),
                ('next_issue_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_projects', to=settings.AUTH_USER_MODEL)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('project_lead', 'Project Lead'), ('ui_ux_designer', 'UI/UX Designer'), ('developer', 'Developer'), ('tester', 'Tester'), ('qa', 'QA'), ('deployment_team', 'Deployment Team'), ('delivery_team', 'Delivery Team')], max_length=25)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='core.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug')], default='task', max_length=10)),
                ('issue_number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('qa', 'Send to QA'), ('done', 'Done')], default='todo', max_length=20)),
                ('rank', models.FloatField(db_index=True, default=0.0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('start_date', models.DateField(blank=True, help_text='Initiated Date (Start)', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Due Date (Deadline)', null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Delivery Date (Actual Completion)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, to='core.label')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_commented', 'Task Commented'), ('project_updated', 'Project Updated'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('team_type', models.CharField(choices=[('development', 'Development'), ('qa', 'QA'), ('design', 'Design'), ('deployment', 'Deployment'), ('delivery', 'Delivery'), ('support', 'Support')], default='development', max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_avatars/')),
                ('color', models.CharField(default='#4F46E5', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.team'),
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('project_lead', 'Project Lead'), ('developer', 'Developer'), ('tester', 'Tester'), ('ui_ux_designer', 'UI/UX Designer'), ('delivery_team', 'Delivery Team'), ('deployment_team', 'Deployment Team'), ('user', 'User')], default='user', max_length=25)),
                ('isProjectLead', models.BooleanField(default=False)),
                ('oauth_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('oauth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('oauth_provider', None), _negated=True), fields=('oauth_provider', 'oauth_id'), name='unique_oauth_per_provider')],
            },
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'role'], name='core_projec_project_fc83c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('user', 'project')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['project'], name='core_team_project_108f79_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['lead'], name='core_team_lead_id_9cc414_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_type'], name='core_team_team_ty_41b22c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='core_team_is_acti_443398_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='core_task_status_e18e62_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'rank'], name='core_task_project_6e1098_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='core_task_assigne_5f3995_idx'),
        ),
    ]
