# Generated by Django 5.2.3 on 2026-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_isprojectlead_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_lead', 'Project Lead'), ('developer', 'Developer'), ('tester', 'Tester'), ('ui_ux_designer', 'UI/UX Designer'), ('delivery_team', 'Delivery Team'), ('deployment_team', 'Deployment Team'), ('user', 'User')], default='user', max_length=25),
        ),
    ]
