# Generated by Django 5.2.3 on 2026-05-29 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expand_role_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDLCPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('requirements', 'Requirements & Backlog'), ('design', 'Design & Prototyping'), ('development', 'Development Sprint'), ('testing', 'QA & Testing'), ('deployment', 'Deployment & Release'), ('monitoring', 'Monitoring & Maintenance')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.SlugField(help_text='URL-safe identifier auto-generated from name.', max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('sdlc_phases', models.ManyToManyField(blank=True, help_text='Which SDLC phases this department participates in.', related_name='departments', to='core.sdlcphase')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(help_text='Stored in ProjectMembership.role. Must be unique per department.', max_length=60)),
                ('transitions', models.JSONField(blank=True, default=dict, help_text='Map of from_status → [to_statuses]. Valid status keys: todo, in_progress, in_review, qa, done.')),
                ('can_manage_all', models.BooleanField(default=False, help_text='Overrides transitions — grants full status access (same as Project Lead).')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'key')},
            },
        ),
    ]
