# Generated by Django 5.2.3 on 2026-05-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_sdlc_department_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sdlc_phases',
        ),
        migrations.RemoveField(
            model_name='departmentrole',
            name='transitions',
        ),
        migrations.AddField(
            model_name='department',
            name='sdlc_phase',
            field=models.CharField(choices=[('requirements', 'Requirements & Backlog'), ('design', 'Design & Prototyping'), ('development', 'Development Sprint'), ('testing', 'QA & Testing'), ('deployment', 'Deployment & Release'), ('monitoring', 'Monitoring & Maintenance'), ('cross_phase', 'Cross-Phase (All Stages)')], default='cross_phase', help_text='Primary SDLC stage this department operates in.', max_length=30),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='can_approve_task',
            field=models.BooleanField(default=False, help_text='In Review / QA → Done'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='can_reject_task',
            field=models.BooleanField(default=False, help_text='In Review / QA → back to In Progress'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='can_send_to_qa',
            field=models.BooleanField(default=False, help_text='In Progress → QA'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='can_start_task',
            field=models.BooleanField(default=True, help_text='Todo → In Progress'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='can_submit_task',
            field=models.BooleanField(default=False, help_text='In Progress → In Review'),
        ),
        migrations.AlterField(
            model_name='department',
            name='key',
            field=models.SlugField(help_text='Auto-generated from name. Used as role identifier.', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentrole',
            name='can_manage_all',
            field=models.BooleanField(default=False, help_text='Full access — overrides all checkboxes above (same as Project Lead).'),
        ),
        migrations.AlterField(
            model_name='departmentrole',
            name='key',
            field=models.SlugField(help_text='Stored in ProjectMembership.role. Auto-generated from name.', max_length=60),
        ),
        migrations.DeleteModel(
            name='SDLCPhase',
        ),
    ]
