# Generated by Django 5.2.3 on 2026-05-06 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_oauth_per_provider',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_status_e18e62_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_project_6e1098_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_assigne_5f3995_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('create_task', 'Create Task'), ('delete_task', 'Delete Task'), ('assign_task', 'Assign Task')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'role'], name='core_projec_project_fc83c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('oauth_provider', None), _negated=True), fields=('oauth_provider', 'oauth_id'), name='unique_oauth_per_provider'),
        ),
    ]
