# Generated by Django 5.2.3 on 2026-05-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_metadata_governance'),
        ('core', '0004_remove_profile_unique_oauth_per_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
    ]
