# Generated by Django 5.2.3 on 2026-05-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_project_milestone_remove_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMilestone',
        ),
    ]
