# Generated by Django 5.2.3 on 2026-05-30 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('business', 'Business'), ('it', 'IT Department'), ('marketing', 'Marketing Team'), ('design', 'Design Team'), ('engineering', 'Engineering'), ('product', 'Product'), ('operations', 'Operations'), ('cross_functional', 'Cross-Functional Team')], max_length=50)),
                ('stage_key', models.CharField(choices=[('todo', 'Initiated / To Do'), ('in_progress', 'Dev / In Progress'), ('in_review', 'UI/UX Review'), ('qa', 'QA / Testing'), ('done', 'Deployment / Done')], max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'stage_key')},
            },
        ),
    ]
