# Generated by Django 5.2.3 on 2026-05-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_department_pipeline_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('team_type', models.CharField(choices=[('initiated', 'Initiated / Planning'), ('design', 'Design / UI-UX'), ('development', 'Development'), ('qa', 'QA / Testing'), ('devops', 'DevOps / Deployment'), ('delivery', 'Delivery')], default='development', max_length=30)),
                ('color', models.CharField(default='#4F46E5', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_teams', to='core.itdepartment')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_order', models.PositiveIntegerField(default=0)),
                ('label_override', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_configs', to='core.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_configs', to='core.itteam')),
            ],
            options={
                'ordering': ['project_id', 'seq_order'],
            },
        ),
    ]
