# Generated by Django 5.2.3 on 2026-04-13 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_label_taskactivity_taskattachment_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_prefix',
            field=models.CharField(default='TF', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('kanban', 'Kanban'), ('scrum', 'Scrum')], default='kanban', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_type',
            field=models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug')], default='task', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='rank',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'rank'], name='core_task_project_6e1098_idx'),
        ),
    ]
