# Generated by Cursor on 2026-04-13

from django.db import migrations
from django.db.models import F


def forwards(apps, schema_editor):
    Task = apps.get_model("core", "Task")

    # Map legacy statuses to new workflow keys
    Task.objects.filter(status="pending").update(status="todo")
    Task.objects.filter(status="testing").update(status="in_review")

    # Ensure reporter is set (default to created_by)
    Task.objects.filter(reporter__isnull=True).update(reporter=F("created_by"))

    # Initialize rank for stable ordering (older first)
    # Use id ordering as a stable proxy without DB-specific functions.
    for i, t in enumerate(Task.objects.order_by("id").only("id"), start=1):
        Task.objects.filter(id=t.id).update(rank=float(i))


def backwards(apps, schema_editor):
    Task = apps.get_model("core", "Task")

    Task.objects.filter(status="todo").update(status="pending")
    Task.objects.filter(status="in_review").update(status="testing")

    # Reporter back to null (best-effort rollback)
    Task.objects.update(reporter=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_project_key_prefix_project_project_type_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

