# Generated by Django 5.2.3 on 2026-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_next_issue_number_and_task_issue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
