# Generated by Django 5.2.3 on 2026-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_taskattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_lead', 'Project Lead'), ('team_lead', 'Team Lead'), ('developer', 'Developer'), ('tester', 'Tester'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
