# Generated by Django 5.2.3 on 2026-07-31 09:23

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_oauth_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_archived'], name='core_task_is_arch_b10b56_idx'),
        ),
    ]
