# Generated by Django 5.2.3 on 2026-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_options_alter_task_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
