# Generated by Django 5.2.3 on 2026-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('visitor', 'Visitor'), ('project_lead', 'Project Lead'), ('product_manager', 'Product Manager'), ('business_analyst', 'Business Analyst'), ('ux_researcher', 'UX Researcher'), ('ui_designer', 'UI Designer'), ('ui_ux_designer', 'UI/UX Designer'), ('frontend_dev', 'Frontend Developer'), ('backend_dev', 'Backend Developer'), ('fullstack_dev', 'Full-Stack Engineer'), ('mobile_dev', 'Mobile Developer'), ('dba', 'Database Administrator'), ('developer', 'Developer'), ('qa_manual', 'Manual QA Tester'), ('qa_automation', 'QA Automation Engineer'), ('security_tester', 'Security / Pen Tester'), ('tester', 'Tester'), ('qa', 'QA'), ('devops_engineer', 'DevOps Engineer'), ('cloud_architect', 'Cloud Architect'), ('deployment_team', 'Deployment Team'), ('data_analyst', 'Data Analyst'), ('data_scientist', 'Data Scientist'), ('helpdesk', 'Helpdesk Technician'), ('ciso', 'CISO / SecOps Engineer'), ('delivery_team', 'Delivery Team')], default='user', max_length=25),
        ),
    ]
