# Generated by Django 5.2.3 on 2026-08-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_visitor_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
