# Generated by Django 5.2.3 on 2026-04-21 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AlterField(
            model_name='projectinvite',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projectinvite',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
