# Generated by Django 5.2.3 on 2026-04-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projectinvite_team_alter_projectinvite_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Delivery Date (Actual Completion)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Initiated Date (Start)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due Date (Deadline)', null=True),
        ),
    ]